services:

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: TIENDA # Nombre de la base de datos
      MYSQL_ROOT_PASSWORD: root        # Contraseña del root
    ports:
      - "3306:3306"

  backend:
    image: docker-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql        # Nombre del servicio MySQL
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: TIENDA
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  frontend:
    image: docker-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge